<style>
	#artis, #artis2 {
		width: 100%;
	}
	.page-header {
		margin-top: 0px;
	}
	.header365 {
		margin-top: -14px;
		background-color: #f4f4f4;
		border-bottom: 1px solid #CCC;
	}
	.main365 {
		background-color: #eaeaea;
	}
	.content365 {
		background-color: #eaeaea;
		width: 95%;
		margin: auto;
		height:100vh;
	}
	.table365 {
		background-color: White;
		width: 100%;
		margin: auto;
	}
	.table365 th {
		font-weight: lighter;
		padding: 5px;
	}
	.table365 td input {
		width: 100%;
	}
	.table365 select {
		width: 100%;	
	}
	.inputText365 {
		border-radius: 0px !important; 
		border: 1px solid black;
	}
	.inputText365N, .inputSelect365N {
		border-radius: 0px !important; 
		border: 0px solid black;
	}
	.content365 label {
		font-style: normal;
    	font-family: 'Segoe UI',tahoma,sans-serif;
    	font-size: 12px;
    	font-variant: normal;
    	font-weight: 400;
	}
	.dynamicsButton {
	    font-weight: lighter;
	    margin-left: 10px;
	    min-width: 105px;
	    min-height: 33px;
	    background-color: #deecf9;
	    border: 1px solid #307BB5;
	    padding: 0 10px;
	    color: #333;
	}
	.dynamicsButton:hover {
		background-color: #eeefff;
		border: 1px solid #307BB3;
	}
</style>

<div class="row header365">
	<div class="col-md-12">
	  	<h4>Ordenes de Devolución</h4>
	</div>
</div>

<div class="row main365">
	<br>
	<div class="col-md-12">
		<form name="devolucion" id="devolucion">
			<div class="content365">
				<div class="row">
					<div class="col-md-2">
						<label for="">CLIENTE</label>
						<br>
						<input class="form-control ui-autocomplete-input inputText365" autocomplete="On" id="cliente" type="text" name="cliente" value="ATP-000001" readonly>
					</div>
					<div class="col-md-2">
						<label for="">FACTURA A DEVOLVER</label>
						<br>
						<input class="form-control inputText365" id="factura" type="text" name="factura" value="ATP-000058">
						<input type="hidden" id="ovOrigen" name="ovOrigen" value=""/>
					</div>
					<div class="col-md-2">
						<label for="">&nbsp;</label>
						<br>
						<button type="button" class="dynamicsButton" onclick="enviar()">
							Enviar
						</button>
					</div>
					<div class="col-md-2"></div>
					<div class="col-md-4">
						<div class="alert alert-warning" role="alert" style="text-align: center;">
							Si no desea eliminar una línea, seleccionar cantidad en 0.
						</div>						
					</div>
				</div>
				<div class="row">
					<div class="col-md-4">
						<label for="">RAZON DE LA DEVOLUCION:</label>
						<br>
						<select class="form-control inputText365" id="razon" type="text" name="razon">
						</select>	
					</div>	
				</div>
				<br>
				<table id="tblOrdenesdevolucion" class="table365" border="1">
					<tr>
						<th>Articulos</th>
						<th>Cantidad</th>
						<th>Lote</th>
					</tr>
					<tr id="firsRow">
						<td>
							<div class="col-md-6" id="artis" name="artis">
								<!-- <select name="lineas" id="lineas" class="form-control inputSelect365N">
									<option value="">0</option>
								</select> -->
							</div>
						</td>
						<td>
							<div class="col-md-3"id="artis2" name="artis2">
								<!-- <select name="cantidad" id="cantidad" class="form-control inputSelect365N">
									<option value="">0</option>
								</select> -->
							</div>
							<div class="col-md-3"id="artis3" name="artis2"></div>
						</td>
						<td></td>
					</tr>
				</table>
				<div class="row">
					<div class="col-lg-4" id="secretariodiv" style="display:none;">
						<label>Secretario de Ventas</label> <select id="secretarioventa" required name="secretarioventa" style="display: block;width: 100%">
							<option value="">Usuario no asignado....</option>
						</select>
					</div>
					<div class="col-lg-4" id="responsablediv" style="display:none;">
						<label>Responsable de Ventas</label> <select id="responsableventa" required name="responsableventa" style="width: 100%;display: block;">
							<option value="">Usuario no asignado....</option>
						</select>
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-md-10"></div>
					<div class="col-md-2" style="text-align: right;">
						<button type="button" class="dynamicsButton" onclick="devolvers()" style="display:none" id ="devolver">
							Devolver
						</button>
					</div>
				</div>
				<br>
				<br>
				<br>
				<div class="row">
					<div class="col-md-12">
						<div id="ordenDevolucionCreada" class="alert alert-success" role="alert" style="text-align: center; font-size: 32px;">
							
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
	
</div>
<script src="<?= JAVASCRIPT_PATH ?>/views/ordenesDevolucion.js?v=<?php echo date("dh"); ?>" type="text/javascript"></script>