<h3>Configuracion de: <?= $this->segmentId?></h3>
<form type="POST" id="segmentFamilyConection">
    <input type="hidden" id="custId" name="segmentId" value="<?= $this->segmentId?>">
    <select class="searchable" id="relationSelect" multiple="multiple"  name="familySelect[]">
        <?php
        $relationExplode = explode(",", $this->familyRelationsArray[0]->Familia);
            foreach ($this->familyArray as $key) {
                $selected = (in_array($key->IDFAMILIA,$relationExplode))? ' selected ' : ' ';
                echo '<option value="'.$key->IDFAMILIA.'" '.$selected.'>'.$key->FAMILIA.'</option>';
            }
        ?>
    </select>
</form>
        <script>
            $('.searchable').multiSelect({
            selectableHeader: "<h3>Familias <p type='button' class='btn btn-success btn-xs sectorToggle' id='selectAll'>Seleccionar Todos</p></h3><input type='text' class='search-input' autocomplete='on' placeholder='Buscar'>",
            selectionHeader: "<h3>Seleccionadas <p type='button' class='btn btn-danger btn-xs sectorToggle' id='deselectAll'>Eliminar Todos</p></h3><input type='text' class='search-input pb-1' autocomplete='on' placeholder='Buscar'>",
            afterInit: function(ms){
                var that = this,
                    $selectableSearch = that.$selectableUl.prev(),
                    $selectionSearch = that.$selectionUl.prev(),
                    selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
                    selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

                that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                .on('keyup', function(e){
                if (e.which === 40){
                    that.$selectableUl.focus();
                    return false;
                }
                });

                that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                .on('keyup', function(e){
                if (e.which == 40){
                    that.$selectionUl.focus();
                    return false;
                }
                });
            },
            afterSelect: function(){
                this.qs1.cache();
                this.qs2.cache();
            },
            afterDeselect: function(){
                this.qs1.cache();
                this.qs2.cache();
            }
            });

            $('#relationSelect').change(function(){
                var formString = $('#segmentFamilyConection').serialize();
                $.post("administracionsectores/setrelation",formString,function(data){
                    }).done(function(data){
                        console.log(data);
                });      
            });

            $('#selectAll').click(function(){
                $('#relationSelect').multiSelect('select_all');
                return false;
            });
            $('#deselectAll').click(function(){
                $('#relationSelect').multiSelect('deselect_all');
                return false;
            });
        </script>