<!-- <script src="<?= JAVASCRIPT_PATH ?>/views/beetrack.js?v=<?php echo date("d"); ?>" type="text/javascript"></script> -->
<div class="row">
    <div class="col-md-12">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="./?"><i class="fa fa-home"> Home</i></a></li>
            <li class="breadcrumb-item active"><i class="fa fa-newspaper-o bg-info"></i> Consulta domicilio</li>
        </ol>        
    </div>
</div>
<div class="panel panel-primary">
            <div class="panel-heading">
                <i class="fa fa-address-card"></i> Consulta de domicilio
            </div>
            <div class="panel-body">
                <div class="row">
                    <form id="inputsFilterTbl">
                    <script type="text/javascript" charset="UTF-8" language="javascript" src="https://beetrack-general.s3-us-west-2.amazonaws.com/widget/JhohW8viHjV6A3TCDlwvFA.json"></script> 
                <script async src="https://app.beetrack.cl/javascript_widget/beetrack_widget.js"></script>
                <div class="panel-heading" id="beetrack_widget" lang="es" api-key="JhohW8viHjV6A3TCDlwvFA"></div>
                    </form>
                </div>
                <br>
                
            </div>
</div>

