<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>inAX - Bulma</title>
	<link rel="stylesheet" href="../../application/assets/bulma/css/bulma.css">
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
</head>
<body>
	<a class="button is-primary">Primary</a>
	<a class="button is-link">Link</a>
	<a class="button is-info">Info</a>
	<a class="button is-success">Success</a>
	<a class="button is-warning">Warning</a>
	<a class="button is-danger">Danger</a>
	<?= $this->layout()->content ?>
</body>
</html>